/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasIdRouteRouteImport } from './routes/ideas/$id/route'
import { Route as IdeasNewIndexRouteImport } from './routes/ideas/new/index'
import { Route as IdeasIdIndexRouteImport } from './routes/ideas/$id/index'
import { Route as IdeasIdEditRouteImport } from './routes/ideas/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdRouteRoute = IdeasIdRouteRouteImport.update({
  id: '/ideas/$id',
  path: '/ideas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasNewIndexRoute = IdeasNewIndexRouteImport.update({
  id: '/ideas/new/',
  path: '/ideas/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdIndexRoute = IdeasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdeasIdRouteRoute,
} as any)
const IdeasIdEditRoute = IdeasIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => IdeasIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas/$id': typeof IdeasIdRouteRouteWithChildren
  '/ideas/': typeof IdeasIndexRoute
  '/ideas/$id/edit': typeof IdeasIdEditRoute
  '/ideas/$id/': typeof IdeasIdIndexRoute
  '/ideas/new/': typeof IdeasNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/ideas/$id/edit': typeof IdeasIdEditRoute
  '/ideas/$id': typeof IdeasIdIndexRoute
  '/ideas/new': typeof IdeasNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas/$id': typeof IdeasIdRouteRouteWithChildren
  '/ideas/': typeof IdeasIndexRoute
  '/ideas/$id/edit': typeof IdeasIdEditRoute
  '/ideas/$id/': typeof IdeasIdIndexRoute
  '/ideas/new/': typeof IdeasNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas/$id'
    | '/ideas/'
    | '/ideas/$id/edit'
    | '/ideas/$id/'
    | '/ideas/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ideas' | '/ideas/$id/edit' | '/ideas/$id' | '/ideas/new'
  id:
    | '__root__'
    | '/'
    | '/ideas/$id'
    | '/ideas/'
    | '/ideas/$id/edit'
    | '/ideas/$id/'
    | '/ideas/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIdRouteRoute: typeof IdeasIdRouteRouteWithChildren
  IdeasIndexRoute: typeof IdeasIndexRoute
  IdeasNewIndexRoute: typeof IdeasNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/ideas/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/new/': {
      id: '/ideas/new/'
      path: '/ideas/new'
      fullPath: '/ideas/new/'
      preLoaderRoute: typeof IdeasNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$id/': {
      id: '/ideas/$id/'
      path: '/'
      fullPath: '/ideas/$id/'
      preLoaderRoute: typeof IdeasIdIndexRouteImport
      parentRoute: typeof IdeasIdRouteRoute
    }
    '/ideas/$id/edit': {
      id: '/ideas/$id/edit'
      path: '/edit'
      fullPath: '/ideas/$id/edit'
      preLoaderRoute: typeof IdeasIdEditRouteImport
      parentRoute: typeof IdeasIdRouteRoute
    }
  }
}

interface IdeasIdRouteRouteChildren {
  IdeasIdEditRoute: typeof IdeasIdEditRoute
  IdeasIdIndexRoute: typeof IdeasIdIndexRoute
}

const IdeasIdRouteRouteChildren: IdeasIdRouteRouteChildren = {
  IdeasIdEditRoute: IdeasIdEditRoute,
  IdeasIdIndexRoute: IdeasIdIndexRoute,
}

const IdeasIdRouteRouteWithChildren = IdeasIdRouteRoute._addFileChildren(
  IdeasIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIdRouteRoute: IdeasIdRouteRouteWithChildren,
  IdeasIndexRoute: IdeasIndexRoute,
  IdeasNewIndexRoute: IdeasNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
